### ISSUE TITLE
[Question]「登ったり降りたり」を許容する方法

### ISSUE THREAD

**Issue by yumetodo** [textlint-ja/textlint-rule-no-doubled-joshi#19]
「登ったり降りたり」というのは助詞の連続かもしれないが、寛容的な言い回しなので許容したい時、設定する方法はありますか？

他にも

- 「それはそれは」
- 「見たことも聞いたことも」
- 「親でも子でも」
- 「してもしなくても」
- 「貴方にとっても私にとっても」

など

**Comment by azu** [comment]
> 「登ったり降りたり」

`"allow": ["たり"]` で無視できるかもしれません。

〜たり〜たりは連続するのが一般的な文法なので、デフォルトの例外にあっても良い気がしますね。
https://github.com/textlint-ja/textlint-rule-prefer-tari-tari

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/releases/tag/3.7.1
で並列助詞は重複の例外にしたので、「登ったり降りたり」はデフォルトで許可されるようになりました。
