### ISSUE TITLE
index baseに変更する

### ISSUE THREAD

**Issue by azu** [textlint-ja/textlint-rule-no-doubled-joshi#21]
https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/blob/8fdcf6336539b94ec4fdab0d517b1f7a3220e2dc/src/no-doubled-joshi.js#L139-L142

もしかしたら column  +  word_position で位置がずれているのかもしれない。
`originalIndexFromIndex` を使うようにすれば、columnずれは起きなくなるはず。

- https://twitter.com/attakei/status/1146419048025976832

**Comment by attakei** [comment]
- textlint-plugin-rst
- textlint-rule-preset-japanese

を利用している状況下で、以下の用なreSTファイルに対して、`textlint`コマンドを実行しています。

```demo.rst
今まで「サイトはNetlify」「スライドはGitLab Pages」といった配信分けをしていたのですが、
「 ``/slides`` にビルドしたスライドを置きたい」という動機のものと、こんな構成を検討しています。

* 最初にtextlintで文法チェック
* ドキュメントを別にビルドしてarticle化
* 複数articleを束ねてFirebaseへデプロイ
```

結果として以下のエラーが出力されています。

```
 7:0  error  一文に二回以上利用されている助詞 "は" がみつかりました。  japanese/no-doubled-joshi

✖ 1 problem (1 error, 0 warnings)
```

状況再現等に使ったファイル・環境等は、 https://gitlab.com/attakei-sandbox/textlint-rst-demo/ に保存しています。 https://gitlab.com/attakei-sandbox/textlint-rst-demo/-/jobs よりエラーの様子が確認できます

**Comment by azu** [comment]
詳細ありがとうございます！

**Comment by azu** [comment]
@attakei https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/releases/tag/3.5.2 で修正してみました。

```
npm i textlint-rule-preset-japanese
```

で中に入ってるtextlint-rule-no-doubled-joshiもアップデートできると思います。

```
npm ls textlint-rule-no-doubled-joshi
textlint-rst-demo@1.0.0 /Users/azu/.ghq/gitlab.com/attakei-sandbox/textlint-rst-demo
└─┬ textlint-rule-preset-japanese@4.0.3
  └── textlint-rule-no-doubled-joshi@3.5.2

```
で確認できます。

頂いた再現リポジトリは次のようになりました。

```
❯ npx textlint demo-*.rst

/Users/azu/.ghq/gitlab.com/attakei-sandbox/textlint-rst-demo/demo-1.rst
  1:22  error  一文に二回以上利用されている助詞 "は" がみつかりました。  japanese/no-doubled-joshi

✖ 1 problem (1 error, 0 warnings)
```

**Comment by attakei** [comment]
こちらのリポジトリでもpackage-lock.json更新後に再実行で確認できました。
ありがとうございました。

↓エビデンス兼ねて、こちらにGitLab-CIでの実行パイプラインを置かせていただきます
https://gitlab.com/attakei-sandbox/textlint-rst-demo/pipelines/69597801
