### ISSUE TITLE
読点がハードコードされている

### ISSUE THREAD

**Issue by pddg** [textlint-ja/textlint-rule-no-doubled-joshi#26]
## 現状の実装

読点はソースコード中にハードコードされており，ユーザが任意に設定することは出来ません．

https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/blob/e11ca0e9df7774bcc76da578b1f227bb365e87f5/src/token-utils.ts#L12-L14

## 起き得る問題

全角ピリオドを使用した文章では，`、`の代わりに全角カンマ（`，`）を用いることが多く見られます．そのため，現状の実装では全角カンマを使用する文章においては正しく動作しません．

## 提案

- ユーザが任意で読点として扱う文字列を変更できるような設定を加える

または

- `、`に加えて`，`も読点として使用する

のいずれかの変更を入れて頂けると幸いです．

refs #25

**Comment by azu** [comment]
> `、`に加えて`，`も読点として使用する

自分はあまり `，` を読点として使う文章を書かないので質問なのですが、
この場合( `，` を読点とした場合)に、その文章中では`、`はどういう扱いになるのでしょうか?

その文章中では`、`を読点として認識したくないような状態ならば、

>    ユーザが任意で読点として扱う文字列を変更できるような設定を加える

の形で実装するのがfalse-positiveを減らせるので妥当かなと思います。

**Comment by pddg** [comment]
混在させて書くことはあまり無いかと．理工系の論文においては`、`の代わりに`，`を，`。`の代わりに`．`を用いるため，`、`や`。`が使われている文章を引用する時以外には使用しないかと思います．

**Comment by pddg** [comment]
`、`を本来の読点以外の意味で使うことは，知る限りでは無いです．

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/releases/tag/3.7.0 で次の変更を加えました

- デフォルトの読点文字として`"，"`(全角カンマ)を追加
- 読点文字を指定できる`commaCharacters`オプションを追加
