### ISSUE TITLE
括弧で囲まれた文章が一文として判定される

### ISSUE THREAD

**Issue by HBonsai** [textlint-ja/textlint-rule-no-doubled-joshi#40]
![image](https://user-images.githubusercontent.com/10624619/157416563-2110d192-76ca-4f2c-a490-89f0337b64b5.png)

「」や各種括弧内の文章が"。"で文を区切っているにもかかわらず一文として判定され、別々の文でも同じ助詞を使っていると指摘対象になってしまいます。小説を書くときは文章を「」で囲うことは珍しくないため、囲っていても通常の文と同様に扱っていただけると助かります。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-no-doubled-joshi/releases/tag/v4.0.2 で修正しました
